#!/bin/bash

cat >.env <<EOF
POSTGRES_USER=$POSTGRES_USER
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=$POSTGRES_DB
EOF

cat >backend/.env <<EOF
Jwt__Secret=$JWT_SECRET
Jwt__RefreshExpiryDays=$JWT_REFRESH_EXPIRY_DAYS
Jwt__ExpiryMinutes=$JWT_EXPIRY_MINUTES
ConnectionStrings__DefaultConnection=$CONNECTION_STRINGS_DEFAULT_CONNECTION
SOURCE_CONN=$CONNECTION_STRINGS_SOURCE_CONNECTION
EOF
