services:
  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: "http://161.35.212.253/api"
    ports:
      - "3000:3000"

  db:
    environment:
      POSTGRES_DB: sushizume-prod
    ports:
      - "5432:5432"

  backend:
    environment:
      NODE_ENV: production
    ports:
      - "8081:5152"
    build: ./backend

  nginx:
    ports:
      - "80:80"
