@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class Address {
   city: text
   district: text
   street: text
   homeNumber: text
   apartamentNumber: text
   floor: integer
   id: text
}
class Category {
   name: text
   id: text
}
class Order {
   email: text
   phone: integer
   peopleNumber: integer
   paymentMethod: text
   new: boolean
   done: boolean
   createdAt: timestamp with time zone
   notesForOrder: text
   addressId: text
   id: text
}
class OrderProduct {
   quantity: integer
   orderId: text
   productId: text
}
class Product {
   name: text
   price: integer
   available: boolean
   visible: boolean
   imagePath: text
   amount: double precision
   amountName: text
   description: text
   categoryId: text
   id: text
}
class ProductItem {
   description: text
   number: integer
   numberPostfix: text
   productId: text
   id: text
}
class __EFMigrationsHistory {
   ProductVersion: varchar(32)
   MigrationId: varchar(150)
}

Order                  -[#595959,plain]-^  Address               : "addressId:id"
OrderProduct           -[#595959,plain]-^  Order                 : "orderId:id"
OrderProduct           -[#595959,plain]-^  Product               : "productId:id"
Product                -[#595959,plain]-^  Category              : "categoryId:id"
ProductItem            -[#595959,plain]-^  Product               : "productId:id"
@enduml
