@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class Address {
   city: text
   district: text
   street: text
   homeNumber: text
   apartamentNumber: text
   floor: integer
   id: text
}
class Category {
   name: text
   id: text
}
class Order {
   email: text
   phone: integer
   peopleNumber: integer
   paymentMethod: text
   new: boolean
   done: boolean
   createdAt: timestamp
   notesForOrder: text
   addressId: text
   id: text
}
class OrderProduct {
   quantity: integer
   productId: text
   orderId: text
}
class Product {
   name: text
   price: integer
   available: boolean
   visible: boolean
   imagePath: text
   amount: real
   amountName: text
   description: text
   categoryId: text
   id: text
}
class temp_ovyhimrgnv {
   o: text
}
class temp_szmvskxeha {
   o: text
}
class temp_ujbltimgit {
   o: text
}

Order            -[#595959,plain]-^  Address         : "addressId:id"
OrderProduct     -[#595959,plain]-^  Order           : "orderId:id"
OrderProduct     -[#595959,plain]-^  Product         : "productId:id"
Product          -[#595959,plain]-^  Category        : "categoryId:id"
@enduml
