#!/bin/bash

cat >.env <<EOF
POSTGRES_USER=$POSTGRES_USER
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=$POSTGRES_DB
EOF

cat >backend/.env <<EOF
Jwt__Secret=$JWT_SECRET
Jwt__RefreshExpiryDays=$JWT_REFRESH_EXPIRY_DAYS
Jwt__ExpiryMinutes=$JWT_EXPIRY_MINUTES
ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=$POSTGRES_DB;Username=$POSTGRES_USER;Password=$POSTGRES_PASSWORD

SOURCE_CONN=$CONNECTION_STRINGS_SOURCE_CONN 
ADMIN_PASSWORD=$ADMIN_PASSWORD
EOF
