name: Deploy to development VPS

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: ./.github/actions/deploy-to-vps
        with:
          remote_path: /home/${{ vars.VPS_USER }}/app
          remote_host: ${{ vars.VPS_HOST }}
          remote_user: ${{ vars.VPS_USER }}
          remote_key: ${{ secrets.VPS_SSH_KEY }}
          postgres_user: ${{ vars.POSTGRES_USER }}
          postgres_password: ${{ secrets.POSTGRES_PASSWORD }}
          postgres_db: ${{ vars.POSTGRES_DB }}
          jwt_secret: ${{ secrets.JWT_SECRET }}
          jwt_expiry_minutes: ${{ vars.JWT_EXPIRY_MINUTES }}
          jwt_refresh_expiry_days: ${{ vars.JWT_REFRESH_EXPIRY_DAYS }}
          conn_str_source: ${{ secrets.CONNECTION_STRINGS_SOURCE_CONN }}
          aspnetcore_environment: Development
          nginx_port: 3000
          nginx_https_port: 3443
          db_port: 5433
          host_url: https://test.sushizume.pl:3443
          admin_password: ${{ secrets.ADMIN_PASSWORD }}
